version: '3.3'

services:
  scanner-gui:
    build: .
    container_name: scanner-gui-container
    ports:
      - "5050:5050"
    volumes:
      - ./Gui_Crawlrice/reports:/app/reports
    restart: unless-stopped